spring:
  security:
    oauth2:
      client:
        registration:
          iam:
            client-id: client
            client-secret: secret
            clientAuthenticationMethod: post
            authorizationGrantType: client_credentials
            provider: as
        provider:
          as:
            token-uri: http://dev.hold.co/as/oauth/token

